name: wallet

services:
  app:
    image: wallet-image
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: wallet-app
    ports:
      - "8000:8000"
    command: "uvicorn --factory app.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../src:/project/src/
      - ../pyproject.toml:/project/pyproject.toml
      - ../uv.lock:/project/uv.lock
    networks:
      - my_network

networks:
  my_network:
    external: true
    driver: bridge
